// Generated by https://quicktype.io

export interface IAuthResponse {
  success: boolean;
  user: User;
  token: string;
  token_refresh: string;
}

// Generated by https://quicktype.io

export interface IUserResponse {
  success: boolean;
  user: User;
}

export interface IUsersResponse {
  success: boolean;
  users: User[];
}

export interface User {
  _id: string;
  name: string;
  email: string;
  password: string;
  isAdmin: boolean;
  __v: number;
  createdAt: string;
  updatedAt: string;
}
